<?php include("./new_tikect_cheker.php");?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>درج نمرات</title>
<style>
	table { 
		width: 70%; 
		border-collapse: collapse; 
		text-align:center
	}
	
	tr:nth-of-type(odd) { 
		background: #eee; 
		text-align:center;
		
	}


 td,th { 
		padding: 6px; 
		border: 1px solid #ccc; 
		text-align:center; 
	}
	

	 tr { 
		
	}
	tr:hover { 
background-color:#FFFF00

	}
	

a:link {
	text-decoration: none;
}
a:visited {
	text-decoration: none;
}
a:hover {
	text-decoration: none;
}
a:active {
	text-decoration: none;
}
body {
	background-image: url(../img/bg.jpg);
}


.uibutton { 
    position: relative; 
    z-index: 1;
    overflow: visible; 
    display: inline-block; 
    padding: 0.3em 0.6em 0.375em; 
    border: 1px solid #999; 
    border-bottom-color: #888;
    margin: 0;
    text-decoration: none; 
    text-align: center;
    font: bold 11px/normal 'lucida grande', tahoma, verdana, arial, sans-serif; 
    white-space: nowrap; 
    cursor: pointer; 
    /* outline: none; */
    color: #333; 
    background-color: #eee;
    background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#f5f6f6), to(#e4e4e3));
    background-image: -moz-linear-gradient(#f5f6f6, #e4e4e3);
    background-image: -o-linear-gradient(#f5f6f6, #e4e4e3);
    background-image: linear-gradient(#f5f6f6, #e4e4e3);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorStr='#f5f6f6', EndColorStr='#e4e4e3'); /* for IE 6 - 9 */
    -webkit-box-shadow: 0 1px 0 rgba(0, 0, 0, 0.1), inset 0 1px 0 #fff;
    -moz-box-shadow: 0 1px 0 rgba(0, 0, 0, 0.1), inset 0 1px 0 #fff;
    box-shadow: 0 1px 0 rgba(0, 0, 0, 0.1), inset 0 1px 0 #fff;
    /* IE hacks */
    zoom: 1; 
    *display: inline; 
}

.uibutton:hover,
.uibutton:focus,
.uibutton:active {
    border-color: #777 #777 #666;
}

.uibutton:active {
    border-color: #aaa;
    background: #ddd;
    filter: none;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
}

/* overrides extra padding on button elements in Firefox */
.uibutton::-moz-focus-inner {
    padding: 0;
    border: 0;
}


 .textbox { 
    border: 1px solid #c4c4c4; 
    height: 20px; 
    width: 50px; 
    font-size: 13px; 
	margin-top:7px;
    padding: 4px 4px 4px 4px; 
    border-radius: 4px; 
    -moz-border-radius: 4px; 
    -webkit-border-radius: 4px; 
    box-shadow: 0px 0px 8px #d9d9d9; 
    -moz-box-shadow: 0px 0px 8px #d9d9d9; 
    -webkit-box-shadow: 0px 0px 8px #d9d9d9; 
	text-align:center;
} 
 
.textbox:focus { 
    outline: none; 
    border: 1px solid #7bc1f7; 
    box-shadow: 0px 0px 8px #7bc1f7; 
    -moz-box-shadow: 0px 0px 8px #7bc1f7; 
    -webkit-box-shadow: 0px 0px 8px #7bc1f7; 
} 


.css_btn_class {
	font-size:16px;
	font-family:Arial;
	font-weight:normal;
	-moz-border-radius:8px;
	-webkit-border-radius:8px;
	border-radius:8px;
	border:1px solid #d83526;
	padding:9px 18px;
	text-decoration:none;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #fe1a00), color-stop(100%, #ce0100) );
	background:-moz-linear-gradient( center top, #fe1a00 5%, #ce0100 100% );
	background:-ms-linear-gradient( top, #fe1a00 5%, #ce0100 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fe1a00', endColorstr='#ce0100');
	background-color:#fe1a00;
	color:#ffffff;
	display:inline-block;
	text-shadow:1px 1px 0px #b23e35;
 	-webkit-box-shadow:inset 1px 1px 0px 0px #f29c93;
 	-moz-box-shadow:inset 1px 1px 0px 0px #f29c93;
 	box-shadow:inset 1px 1px 0px 0px #f29c93;
}.css_btn_class:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #ce0100), color-stop(100%, #fe1a00) );
	background:-moz-linear-gradient( center top, #ce0100 5%, #fe1a00 100% );
	background:-ms-linear-gradient( top, #ce0100 5%, #fe1a00 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ce0100', endColorstr='#fe1a00');
	background-color:#ce0100;
}.css_btn_class:active {
	position:relative;
	top:1px;
}
/* This css button was generated by http://html-generator.weebly.com */


</style>


</head>


<script>
function mhh()
{
var b=parseFloat(document.form1.mss.value);
var t=0;
for(var i=0 ; i<b ; i++)
{
		if(document.form1['text'+i].value<=20 && document.form1['text'+i].value>=0)
			{
				if((i+1)==b)
				{
					document.form1.send.type="submit" ;
					document.form1.action="./insert_marks.php" ;
			    }
		   }
	   else{alert ("نمره نمی توانید بیشتر از 20 و کمتر از 0 باشد"+"  "+"("+"کاربر"+(i+1)+")");t=1;if(t==1) continue start;}
}
start:
t=0;

}

</script>
<body>
<center>
<?php

//include("./new_tikect_cheker.php");	// 	<== IS INTO session_start();					



?>
<form action="insert_marks.php" method="post" name="form1" id="form1">

<table border="1" cellpadding="4" cellspacing="0" >
<td style="font:Tahoma ;color:#9900FF" align="center"> <b>  نمره  </b> </td>
<td style="font:Tahoma ;color:#9900FF" align="center"> <b>   نام خانوادگی   </b> </td>
<td style="font:Tahoma ;color:#9900FF" align="center"> <b>    نام    </b> </td>
<td style="font:Tahoma ;color:#9900FF" align="center"> <b>    #    </b> </td>

<?php
if(!isset($_SESSION['sqlslt']))
{
echo '<script> alert ("شما جدول ای انتخاب نکرده اید بنابراین به صفحه انتخاب منتقل می شوید");</script>';			
header("location:./Login.php");
}
else
{


include("../Config.php");
$sql="Select * from  ".$_SESSION['sqlslt']." ";
$result=mysqli_query($con,$sql);
@$num=mysqli_num_rows($result);
echo "<input type=\"hidden\" name=\"mss\" value=\"$num\" />";
for($i=0;$i<$num;$i++)
{
$row = mysqli_fetch_row($result);
$cmd=$i+1;
echo "<tr>";
echo "<td align='center'> <b> <input type=\"text\" name=".'text'."".$i." value=\"$row[18]\" size=\"5\" maxlength=\"5\" class=\"textbox\" \" > </b> </td>";
echo "<td align='center'> <b> ".DeCryption($row[1])." </b> </td>";
echo "<td align='center'> <b> ".DeCryption($row[0])." </b> </td>";
echo "<td align='center'> <b> ".$cmd." </b> </td>";
echo "</tr>";


}



if(isset($_POST['send']))
{
$sqll="Select * from  ".$_SESSION['sqlslt']." ";
$resultt=mysqli_query($con,$sqll);
@$numm=mysqli_num_rows($resultt);
for($i=0;$i<$numm;$i++)
{
@$roww = mysqli_fetch_row($resultt);
$query="UPDATE ".$_SESSION['sqlslt']." SET mark='".$_POST['text'."".$i]."' WHERE pass='".$roww[13]."' ";
$resulttt=mysqli_query($con,$query);
if(!$resulttt){echo "not";}

}
echo '<script> alert ("تغییرات و درج نمرات با موفقیت انجام شد");</script>';
echo  '<meta http-equiv="refresh" content="0;URL=./insert_marks.php">';

	

}

}



?>
</table><br /><br />
<input type="submit" name="send" value="درج/تغییر"  class="css_btn_class" />
<a href="./Admin_cp.php" class="css_btn_class">بازگشت</a>
</form>
</center>
</body>
</html>
